import { useEffect } from 'react';
import { loadGoogleFonts } from '@/utils/loadGoogleFonts';

export function ThemeProvider({ children, theme }) {
    useEffect(() => {
        if (!theme) return;

        const root = document.documentElement;

        // Apply CSS custom properties
        if (theme.colors) {
            Object.entries(theme.colors).forEach(([key, value]) => {
                root.style.setProperty(`--color-${key}`, value);
            });
        }
        if (theme.fonts) {
            root.style.setProperty('--font-heading', `'${theme.fonts.heading}', sans-serif`);
            root.style.setProperty('--font-body', `'${theme.fonts.body}', sans-serif`);

            const fontsToLoad = [theme.fonts.heading];
            if (theme.fonts.body && theme.fonts.body !== theme.fonts.heading) {
                fontsToLoad.push(theme.fonts.body);
            }
            if (fontsToLoad.length > 0) loadGoogleFonts(fontsToLoad);
        }
        if (theme.styles?.borderRadius) {
            root.style.setProperty('--border-radius', theme.styles.borderRadius);
        }

        // Apply data attrs for CSS targeting
        if (theme.id)              document.body.className = `theme-${theme.id}`;
        if (theme.styles?.layout)       document.body.setAttribute('data-layout', theme.styles.layout);
        if (theme.styles?.navbarStyle)  document.body.setAttribute('data-navbar-style', theme.styles.navbarStyle);
        if (theme.styles?.cardStyle)    document.body.setAttribute('data-card-style', theme.styles.cardStyle);
        if (theme.styles?.heroStyle)    document.body.setAttribute('data-hero-style', theme.styles.heroStyle);
        if (theme.styles?.buttonStyle)  document.body.setAttribute('data-button-style', theme.styles.buttonStyle);

        // Inject OPAC-specific CSS using actual color values.
        // Tailwind utility classes are compile-time — they cannot read CSS vars at runtime,
        // so we inject a <style> block that overrides the hardcoded classes.
        const isDark     = theme.styles?.navbarStyle === 'dark';
        const primary    = theme.colors?.primary    || '#3B82F6';
        const background = theme.colors?.background || '#F8FAFC';
        const textColor  = theme.colors?.text       || '#0B1220';

        const navbarBg       = isDark ? background          : primary;
        const navbarTextCol  = isDark ? primary              : 'rgba(255,255,255,0.95)';
        const navbarHoverCol = isDark ? 'rgba(255,255,255,0.95)' : 'white';
        // Footer: use brand-950 if available (eLibrary Modern has it), otherwise primary or near-black for dark
        const footerBg = isDark
            ? '#070b16'
            : (theme.colors?.['brand-950'] || primary);

        let styleEl = document.getElementById('opac-theme-styles');
        if (!styleEl) {
            styleEl = document.createElement('style');
            styleEl.id = 'opac-theme-styles';
            document.head.appendChild(styleEl);
        }

        styleEl.textContent = `
/* ── OPAC theme injection (generated by ThemeProvider) ── */
.opac-page-bg {
    background-color: ${background} !important;
    color: ${textColor} !important;
}
.opac-navbar-themed {
    background-color: ${navbarBg} !important;
    border-color: ${isDark ? primary + '30' : 'transparent'} !important;
    backdrop-filter: none !important;
    -webkit-backdrop-filter: none !important;
}
.opac-navbar-themed a,
.opac-navbar-themed button,
.opac-navbar-themed label {
    color: ${navbarTextCol} !important;
}
.opac-navbar-themed a:hover,
.opac-navbar-themed button:hover {
    color: ${navbarHoverCol} !important;
    opacity: 0.85;
}
.opac-navbar-themed svg {
    stroke: ${navbarTextCol} !important;
}
.opac-footer-themed {
    background-color: ${footerBg} !important;
}
        `;

        // Custom CSS
        if (theme.custom_css) {
            let customEl = document.getElementById('custom-theme-css');
            if (!customEl) {
                customEl = document.createElement('style');
                customEl.id = 'custom-theme-css';
                document.head.appendChild(customEl);
            }
            customEl.textContent = theme.custom_css;
        }

    }, [theme]);

    return <>{children}</>;
}
